# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    commit-message:
      prefix: deps
      include: scope
    reviewers:
      - njfamirm
    schedule:
      interval: weekly
      time: '08:30'
      day: thursday
    labels:
      - ci
      - priority-low
      - maintenance
    groups:
      github-actions:
        patterns:
          - '*'
