# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build, Lint, and Test Project

# Required permission on the caller workflow
# permissions:
#   contents: read

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        default: 'lts/*'
        type: string

jobs:
  main:
    name: Build, Lint, and Test Project
    runs-on: blacksmith-2vcpu-ubuntu-2404
    env:
      WIREIT_LOGGER: metrics

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v7

      - name: 🛠️ Setup Node.js Corepack
        run: corepack enable

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: 🗂️ Cache .cache folders
        uses: actions/cache@v6
        with:
          path: packages/**/.cache
          key: ${{ runner.os }}-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: 📥 Install Dependencies
        run: yarn install --immutable

      - name: 🏗️ Build
        run: yarn build

      - name: 🧹 Run ESLint
        run: yarn lint

      - name: 🧪 Run Tests
        run: yarn test
