# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build, Lint, and Test Project

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        default: 'lts/*'
        type: string

permissions:
  contents: read

jobs:
  main:
    name: Build, Lint, and Test Project
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: 🛠️ Setup Node.js Corepack
        run: corepack enable

      - name: 📦 Get Yarn Config
        id: yarn_config
        run: echo "cache_folder=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: 🗄️ Cache Layer
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn_config.outputs.cache_folder }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 📥 Install Dependencies
        run: yarn install --immutable

      - name: 🏗️ Build
        run: yarn build
        env:
          WIREIT_LOGGER: metrics

      - name: 🧹 Run ESLint
        run: yarn lint
        env:
          WIREIT_LOGGER: metrics

      - name: 🧪 Run Tests
        run: yarn test
        env:
          WIREIT_LOGGER: metrics
