# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync labels
on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token'
        required: true

jobs:
  main:
    name: Sync labels
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
