# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Sync labels

# Required permission on the caller workflow
# permissions:
#   contents: read
#   issues: write

on:
  workflow_call:

jobs:
  main:
    name: Sync labels
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v5

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
